# Generated by Django 5.2.4 on 2025-09-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(db_index=True, max_length=20, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.FloatField(default=0.0)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('vibe_classification', models.CharField(blank=True, choices=[('energetic', 'Energetic'), ('aesthetic', 'Aesthetic'), ('educational', 'Educational'), ('entertaining', 'Entertaining'), ('promotional', 'Promotional')], max_length=20)),
                ('audio_name', models.CharField(blank=True, max_length=200)),
                ('audio_artist', models.CharField(blank=True, max_length=200)),
                ('audio_duration', models.FloatField(default=0.0)),
                ('audio_is_original', models.BooleanField(default=False)),
                ('scene_changes', models.IntegerField(default=0)),
                ('activity_level', models.FloatField(default=0.0)),
                ('face_time_percentage', models.FloatField(default=0.0)),
                ('has_captions', models.BooleanField(default=False)),
                ('is_branded_content', models.BooleanField(default=False)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('effects_used', models.JSONField(blank=True, default=list)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='influencers.influencer')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
