# Generated by Django 5.2.4 on 2025-09-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("influencers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reel_id", models.CharField(max_length=100, unique=True)),
                ("shortcode", models.CharField(max_length=50)),
                ("video_url", models.URLField()),
                ("thumbnail_url", models.URLField()),
                (
                    "thumbnail_local",
                    models.ImageField(
                        blank=True, null=True, upload_to="reel_thumbnails/"
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("post_date", models.DateTimeField()),
                ("duration", models.PositiveIntegerField(default=0)),
                ("detected_events", models.JSONField(default=list)),
                ("vibe_classification", models.CharField(blank=True, max_length=50)),
                ("descriptive_tags", models.JSONField(default=list)),
                ("is_analyzed", models.BooleanField(default=False)),
                ("analysis_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reels",
                        to="influencers.influencer",
                    ),
                ),
            ],
            options={
                "ordering": ["-post_date"],
            },
        ),
        migrations.CreateModel(
            name="ReelAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_changes", models.PositiveIntegerField(default=0)),
                ("activity_level", models.CharField(default="medium", max_length=20)),
                ("audio_detected", models.BooleanField(default=False)),
                ("primary_subject", models.CharField(blank=True, max_length=100)),
                ("environment", models.CharField(blank=True, max_length=50)),
                ("time_of_day", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="reels.reel",
                    ),
                ),
            ],
        ),
    ]
