# Generated by Django 5.2.4 on 2025-09-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('shortcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('views_count', models.BigIntegerField(db_index=True, default=0)),
                ('likes_count', models.BigIntegerField(db_index=True, default=0)),
                ('comments_count', models.BigIntegerField(db_index=True, default=0)),
                ('post_date', models.DateTimeField(db_index=True)),
                ('duration', models.IntegerField(default=0)),
                ('detected_events', models.TextField(blank=True, default='[]', help_text='JSON list of detected events')),
                ('vibe_classification', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('descriptive_tags', models.TextField(blank=True, default='[]', help_text='JSON list of descriptive tags')),
                ('is_analyzed', models.BooleanField(db_index=True, default=False)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='influencers.influencer')),
            ],
            options={
                'db_table': 'reels',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='ReelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_changes', models.IntegerField(default=0)),
                ('activity_level', models.CharField(default='medium', max_length=20)),
                ('audio_detected', models.BooleanField(default=False)),
                ('primary_subject', models.CharField(blank=True, max_length=50, null=True)),
                ('environment', models.CharField(blank=True, max_length=50, null=True)),
                ('time_of_day', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='reels.reel')),
            ],
            options={
                'db_table': 'reel_analyses',
            },
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['influencer', '-post_date'], name='reels_influen_fc1b27_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['views_count'], name='reels_views_c_087d67_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['vibe_classification'], name='reels_vibe_cl_87c6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['is_analyzed'], name='reels_is_anal_835ed3_idx'),
        ),
    ]
