# Generated by Django 5.2.4 on 2025-09-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(db_index=True, default=0)),
                ('following_count', models.BigIntegerField(default=0)),
                ('posts_count', models.BigIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('engagement_rate', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5)),
                ('avg_likes', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('avg_comments', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('scrape_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'influencers',
                'ordering': ['-followers_count'],
                'indexes': [models.Index(fields=['username'], name='influencers_usernam_9d2e3b_idx'), models.Index(fields=['followers_count'], name='influencers_followe_55146c_idx'), models.Index(fields=['engagement_rate'], name='influencers_engagem_0c449b_idx'), models.Index(fields=['is_verified'], name='influencers_is_veri_2ef042_idx')],
            },
        ),
    ]
