# Generated by Django 5.2.4 on 2025-09-28 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('fitness', 'Fitness & Health'), ('technology', 'Technology'), ('travel', 'Travel & Adventure'), ('food', 'Food & Cooking'), ('fashion', 'Fashion & Style'), ('lifestyle', 'Lifestyle'), ('business', 'Business'), ('entertainment', 'Entertainment')], default='lifestyle', max_length=50)),
                ('engagement_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('avg_likes', models.IntegerField(default=0)),
                ('avg_comments', models.IntegerField(default=0)),
                ('avg_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('content_themes', models.JSONField(blank=True, default=dict)),
                ('posting_patterns', models.JSONField(blank=True, default=dict)),
                ('audience_insights', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-followers_count'],
            },
        ),
    ]
