# Generated by Django 5.2.4 on 2025-09-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("profile_pic_url", models.URLField(blank=True)),
                (
                    "profile_pic_local",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("followers_count", models.PositiveIntegerField(default=0)),
                ("following_count", models.PositiveIntegerField(default=0)),
                ("posts_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_likes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_comments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "engagement_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("bio", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                ("scrape_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-followers_count"],
            },
        ),
    ]
