# Generated by Django 5.2.4 on 2025-09-28 09:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(db_index=True, default='', max_length=20, unique=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('carousel', 'Carousel'), ('reel', 'Reel')], default='photo', max_length=20)),
                ('media_url', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('analysis_status', models.CharField(default='pending', max_length=20)),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('vibe_classification', models.CharField(blank=True, choices=[('aesthetic', 'Aesthetic'), ('casual', 'Casual'), ('professional', 'Professional'), ('energetic', 'Energetic'), ('luxury', 'Luxury')], default='casual', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('dominant_colors', models.JSONField(blank=True, default=list)),
                ('detected_objects', models.JSONField(blank=True, default=list)),
                ('face_count', models.IntegerField(default=0)),
                ('text_overlay_detected', models.BooleanField(default=False)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('auto_tags', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('location_coords', models.JSONField(blank=True, default=dict)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='influencers.influencer')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
