# Generated by Django 5.2.4 on 2025-09-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("influencers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=100, unique=True)),
                ("shortcode", models.CharField(max_length=50)),
                ("image_url", models.URLField()),
                (
                    "image_local",
                    models.ImageField(blank=True, null=True, upload_to="post_images/"),
                ),
                ("caption", models.TextField(blank=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("post_date", models.DateTimeField()),
                ("is_video", models.BooleanField(default=False)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("vibe_classification", models.CharField(blank=True, max_length=50)),
                (
                    "quality_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_analyzed", models.BooleanField(default=False)),
                ("analysis_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="influencers.influencer",
                    ),
                ),
            ],
            options={
                "ordering": ["-post_date"],
            },
        ),
        migrations.CreateModel(
            name="PostAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lighting_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "composition_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "visual_appeal_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("detected_objects", models.JSONField(default=list)),
                ("dominant_colors", models.JSONField(default=list)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("mood", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="posts.post",
                    ),
                ),
            ],
        ),
    ]
