# Generated by Django 5.2.4 on 2025-09-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("influencers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudienceDemographics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_13_17",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "age_18_24",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "age_25_34",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "age_35_44",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "age_45_54",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "age_55_plus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "male_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "female_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("top_countries", models.JSONField(default=list)),
                ("top_cities", models.JSONField(default=list)),
                ("peak_activity_hours", models.JSONField(default=list)),
                ("most_active_days", models.JSONField(default=list)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "influencer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics",
                        to="influencers.influencer",
                    ),
                ),
            ],
        ),
    ]
