# Generated by Django 5.2.4 on 2025-09-28 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_followers_analyzed', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('data_points_used', models.IntegerField(default=0)),
                ('age_13_17', models.FloatField(default=0.0)),
                ('age_18_24', models.FloatField(default=0.0)),
                ('age_25_34', models.FloatField(default=0.0)),
                ('age_35_44', models.FloatField(default=0.0)),
                ('age_45_54', models.FloatField(default=0.0)),
                ('age_55_plus', models.FloatField(default=0.0)),
                ('male_percentage', models.FloatField(default=0.0)),
                ('female_percentage', models.FloatField(default=0.0)),
                ('other_percentage', models.FloatField(default=0.0)),
                ('top_countries', models.JSONField(blank=True, default=list)),
                ('top_cities', models.JSONField(blank=True, default=list)),
                ('top_languages', models.JSONField(blank=True, default=list)),
                ('interest_categories', models.JSONField(blank=True, default=list)),
                ('device_distribution', models.JSONField(blank=True, default=dict)),
                ('platform_usage', models.JSONField(blank=True, default=dict)),
                ('peak_activity_hours', models.JSONField(blank=True, default=list)),
                ('engagement_by_day', models.JSONField(blank=True, default=dict)),
                ('fake_followers_percentage', models.FloatField(default=0.0)),
                ('inactive_followers_percentage', models.FloatField(default=0.0)),
                ('high_quality_followers_percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('next_update_scheduled', models.DateTimeField(blank=True, null=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='influencers.influencer')),
            ],
            options={
                'verbose_name_plural': 'Demographics',
            },
        ),
    ]
