# Generated by Django 5.2.4 on 2025-09-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_13_17', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('age_18_24', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('age_25_34', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('age_35_44', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('age_45_54', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('age_55_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('male_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('female_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('top_countries', models.TextField(blank=True, default='[]', help_text='JSON list of countries')),
                ('top_cities', models.TextField(blank=True, default='[]', help_text='JSON list of cities')),
                ('peak_activity_hours', models.TextField(blank=True, default='[]', help_text='JSON list of hours')),
                ('most_active_days', models.TextField(blank=True, default='[]', help_text='JSON list of days')),
                ('confidence_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('inference_date', models.DateTimeField(auto_now=True)),
                ('data_points_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='influencers.influencer')),
            ],
            options={
                'verbose_name_plural': 'Audience Demographics',
                'db_table': 'audience_demographics',
            },
        ),
    ]
